# Generated by Django 4.1.7 on 2023-03-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.CharField(max_length=200)),
                ('UTC', models.CharField(max_length=200)),
                ('TKN_ID', models.CharField(max_length=200)),
                ('TMPR_CHECK', models.CharField(max_length=200)),
            ],
        ),
    ]
