# Generated by Django 4.1.7 on 2023-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scandata',
            name='TMPR_CHECK',
        ),
        migrations.AddField(
            model_name='scandata',
            name='Model',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='scandata',
            name='TAMP_CHCK',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='TKN_ID',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='UID',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='UTC',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
