# Generated by Django 4.1.7 on 2023-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_scandata_validscan_alter_scandata_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandata',
            name='TAMP_CHCK',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='TKN_ID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='UID',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='scandata',
            name='UTC',
            field=models.CharField(default='', max_length=200),
        ),
    ]
