# Generated by Django 4.1.7 on 2023-04-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_scandata_tamp_chck_alter_scandata_tkn_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandata',
            name='Model',
            field=models.CharField(default='', max_length=200),
        ),
    ]
