# Generated by Django 4.1.7 on 2023-04-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_scandata_shoeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandata',
            name='ValidScan',
            field=models.CharField(default='', max_length=200),
        ),
    ]
